// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passw0rd.proto

package passw0rd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatabaseRecord struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Record               []byte   `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRecord) Reset()         { *m = DatabaseRecord{} }
func (m *DatabaseRecord) String() string { return proto.CompactTextString(m) }
func (*DatabaseRecord) ProtoMessage()    {}
func (*DatabaseRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{0}
}

func (m *DatabaseRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRecord.Unmarshal(m, b)
}
func (m *DatabaseRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRecord.Marshal(b, m, deterministic)
}
func (m *DatabaseRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRecord.Merge(m, src)
}
func (m *DatabaseRecord) XXX_Size() int {
	return xxx_messageInfo_DatabaseRecord.Size(m)
}
func (m *DatabaseRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRecord proto.InternalMessageInfo

func (m *DatabaseRecord) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DatabaseRecord) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

type EnrollmentRequest struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentRequest) Reset()         { *m = EnrollmentRequest{} }
func (m *EnrollmentRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollmentRequest) ProtoMessage()    {}
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{1}
}

func (m *EnrollmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentRequest.Unmarshal(m, b)
}
func (m *EnrollmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentRequest.Marshal(b, m, deterministic)
}
func (m *EnrollmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentRequest.Merge(m, src)
}
func (m *EnrollmentRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollmentRequest.Size(m)
}
func (m *EnrollmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentRequest proto.InternalMessageInfo

func (m *EnrollmentRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type EnrollmentResponse struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Response             []byte   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentResponse) Reset()         { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()    {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{2}
}

func (m *EnrollmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentResponse.Unmarshal(m, b)
}
func (m *EnrollmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentResponse.Marshal(b, m, deterministic)
}
func (m *EnrollmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentResponse.Merge(m, src)
}
func (m *EnrollmentResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollmentResponse.Size(m)
}
func (m *EnrollmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentResponse proto.InternalMessageInfo

func (m *EnrollmentResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EnrollmentResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

type VerifyPasswordRequest struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Request              []byte   `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordRequest) Reset()         { *m = VerifyPasswordRequest{} }
func (m *VerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordRequest) ProtoMessage()    {}
func (*VerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{3}
}

func (m *VerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordRequest.Unmarshal(m, b)
}
func (m *VerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordRequest.Merge(m, src)
}
func (m *VerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordRequest.Size(m)
}
func (m *VerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordRequest proto.InternalMessageInfo

func (m *VerifyPasswordRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VerifyPasswordRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

type VerifyPasswordResponse struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordResponse) Reset()         { *m = VerifyPasswordResponse{} }
func (m *VerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordResponse) ProtoMessage()    {}
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{4}
}

func (m *VerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordResponse.Unmarshal(m, b)
}
func (m *VerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *VerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordResponse.Merge(m, src)
}
func (m *VerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordResponse.Size(m)
}
func (m *VerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordResponse proto.InternalMessageInfo

func (m *VerifyPasswordResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

type VersionedUpdateToken struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	UpdateToken          []byte   `protobuf:"bytes,2,opt,name=update_token,json=updateToken,proto3" json:"update_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionedUpdateToken) Reset()         { *m = VersionedUpdateToken{} }
func (m *VersionedUpdateToken) String() string { return proto.CompactTextString(m) }
func (*VersionedUpdateToken) ProtoMessage()    {}
func (*VersionedUpdateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{5}
}

func (m *VersionedUpdateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedUpdateToken.Unmarshal(m, b)
}
func (m *VersionedUpdateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedUpdateToken.Marshal(b, m, deterministic)
}
func (m *VersionedUpdateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedUpdateToken.Merge(m, src)
}
func (m *VersionedUpdateToken) XXX_Size() int {
	return xxx_messageInfo_VersionedUpdateToken.Size(m)
}
func (m *VersionedUpdateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedUpdateToken.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedUpdateToken proto.InternalMessageInfo

func (m *VersionedUpdateToken) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionedUpdateToken) GetUpdateToken() []byte {
	if m != nil {
		return m.UpdateToken
	}
	return nil
}

type HttpError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpError) Reset()         { *m = HttpError{} }
func (m *HttpError) String() string { return proto.CompactTextString(m) }
func (*HttpError) ProtoMessage()    {}
func (*HttpError) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea098cf24212aa17, []int{6}
}

func (m *HttpError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpError.Unmarshal(m, b)
}
func (m *HttpError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpError.Marshal(b, m, deterministic)
}
func (m *HttpError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpError.Merge(m, src)
}
func (m *HttpError) XXX_Size() int {
	return xxx_messageInfo_HttpError.Size(m)
}
func (m *HttpError) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpError.DiscardUnknown(m)
}

var xxx_messageInfo_HttpError proto.InternalMessageInfo

func (m *HttpError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DatabaseRecord)(nil), "passw0rd.DatabaseRecord")
	proto.RegisterType((*EnrollmentRequest)(nil), "passw0rd.EnrollmentRequest")
	proto.RegisterType((*EnrollmentResponse)(nil), "passw0rd.EnrollmentResponse")
	proto.RegisterType((*VerifyPasswordRequest)(nil), "passw0rd.VerifyPasswordRequest")
	proto.RegisterType((*VerifyPasswordResponse)(nil), "passw0rd.VerifyPasswordResponse")
	proto.RegisterType((*VersionedUpdateToken)(nil), "passw0rd.VersionedUpdateToken")
	proto.RegisterType((*HttpError)(nil), "passw0rd.HttpError")
}

func init() { proto.RegisterFile("passw0rd.proto", fileDescriptor_ea098cf24212aa17) }

var fileDescriptor_ea098cf24212aa17 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x91, 0xda, 0x8e, 0xb5, 0x60, 0xd0, 0xb2, 0x78, 0xaa, 0x39, 0xf5, 0xa2, 0x08,
	0x7a, 0xf1, 0x2a, 0x16, 0x44, 0x2f, 0x12, 0xb5, 0x57, 0x49, 0x9b, 0x51, 0x8a, 0x6d, 0x26, 0xce,
	0x64, 0x15, 0xff, 0xbd, 0xec, 0x6e, 0x56, 0x4b, 0xc1, 0xf5, 0x96, 0x47, 0xbe, 0x7c, 0xf3, 0x92,
	0xc0, 0x20, 0x58, 0x91, 0xcf, 0x33, 0x76, 0xa7, 0x81, 0x29, 0x92, 0xea, 0x36, 0x59, 0x5f, 0xc1,
	0xe0, 0xda, 0x46, 0x3b, 0xb3, 0x82, 0x06, 0xe7, 0xc4, 0x4e, 0xe5, 0xb0, 0xf3, 0x81, 0x2c, 0x0b,
	0xf2, 0x79, 0x36, 0xca, 0xc6, 0x7b, 0xa6, 0x89, 0x6a, 0x08, 0x1d, 0xae, 0x98, 0x7c, 0x6b, 0x94,
	0x8d, 0xfb, 0x26, 0x25, 0x7d, 0x02, 0xfb, 0x13, 0xcf, 0xb4, 0x5c, 0xae, 0xd0, 0x47, 0x83, 0xef,
	0x05, 0x4a, 0xfc, 0x5b, 0xa3, 0x6f, 0x41, 0xad, 0xe3, 0x12, 0xc8, 0x0b, 0xb6, 0x8c, 0x3d, 0x82,
	0x2e, 0x27, 0x2a, 0x0d, 0xfe, 0xc9, 0xfa, 0x0e, 0x0e, 0xa7, 0xc8, 0x8b, 0x97, 0xaf, 0xfb, 0xf2,
	0x42, 0xc4, 0xee, 0xdf, 0xf1, 0xe5, 0x0e, 0xd7, 0x50, 0xb2, 0x35, 0x51, 0x5f, 0xc0, 0x70, 0x53,
	0x96, 0xca, 0xad, 0x57, 0xc8, 0x36, 0x2a, 0x3c, 0xc0, 0xc1, 0xb4, 0x56, 0xa3, 0x7b, 0x0a, 0xce,
	0x46, 0x7c, 0xa4, 0x37, 0xf4, 0x2d, 0x0d, 0x8e, 0xa1, 0x5f, 0x54, 0xe0, 0x73, 0x2c, 0xc9, 0x54,
	0x63, 0xb7, 0xf8, 0x3d, 0xac, 0x2f, 0xa1, 0x77, 0x13, 0x63, 0x98, 0x30, 0x13, 0x2b, 0x05, 0xdb,
	0x73, 0x72, 0x98, 0x34, 0xd5, 0xba, 0xb4, 0xaf, 0x50, 0xc4, 0xbe, 0xd6, 0x6f, 0xd2, 0x33, 0x4d,
	0x9c, 0x75, 0xaa, 0x2f, 0x3e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x48, 0x72, 0xb4, 0xf4,
	0x01, 0x00, 0x00,
}
