//
// Copyright (c) 2015-2020, Virgil Security, Inc.
//
// Lead Maintainer: Virgil Security Inc. <support@virgilsecurity.com>
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     (1) Redistributions of source code must retain the above copyright notice, this
//     list of conditions and the following disclaimer.
//
//     (2) Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//
//     (3) Neither the name of virgil nor the names of its
//     contributors may be used to endorse or promote products derived from
//     this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: purekitV3_grant.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EncryptedGrantHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId      string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId          []byte `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CreationDate   uint64 `protobuf:"varint,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ExpirationDate uint64 `protobuf:"varint,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
}

func (x *EncryptedGrantHeader) Reset() {
	*x = EncryptedGrantHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purekitV3_grant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedGrantHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedGrantHeader) ProtoMessage() {}

func (x *EncryptedGrantHeader) ProtoReflect() protoreflect.Message {
	mi := &file_purekitV3_grant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedGrantHeader.ProtoReflect.Descriptor instead.
func (*EncryptedGrantHeader) Descriptor() ([]byte, []int) {
	return file_purekitV3_grant_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedGrantHeader) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EncryptedGrantHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EncryptedGrantHeader) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *EncryptedGrantHeader) GetCreationDate() uint64 {
	if x != nil {
		return x.CreationDate
	}
	return 0
}

func (x *EncryptedGrantHeader) GetExpirationDate() uint64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

type EncryptedGrant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedPhek []byte `protobuf:"bytes,2,opt,name=encrypted_phek,json=encryptedPhek,proto3" json:"encrypted_phek,omitempty"`
	Header        []byte `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *EncryptedGrant) Reset() {
	*x = EncryptedGrant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purekitV3_grant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedGrant) ProtoMessage() {}

func (x *EncryptedGrant) ProtoReflect() protoreflect.Message {
	mi := &file_purekitV3_grant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedGrant.ProtoReflect.Descriptor instead.
func (*EncryptedGrant) Descriptor() ([]byte, []int) {
	return file_purekitV3_grant_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedGrant) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedGrant) GetEncryptedPhek() []byte {
	if x != nil {
		return x.EncryptedPhek
	}
	return nil
}

func (x *EncryptedGrant) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_purekitV3_grant_proto protoreflect.FileDescriptor

var file_purekitV3_grant_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x75, 0x72, 0x65, 0x6b, 0x69, 0x74, 0x56, 0x33, 0x5f, 0x67, 0x72, 0x61, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0xb3, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x69, 0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x70,
	0x68, 0x65, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x50, 0x68, 0x65, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purekitV3_grant_proto_rawDescOnce sync.Once
	file_purekitV3_grant_proto_rawDescData = file_purekitV3_grant_proto_rawDesc
)

func file_purekitV3_grant_proto_rawDescGZIP() []byte {
	file_purekitV3_grant_proto_rawDescOnce.Do(func() {
		file_purekitV3_grant_proto_rawDescData = protoimpl.X.CompressGZIP(file_purekitV3_grant_proto_rawDescData)
	})
	return file_purekitV3_grant_proto_rawDescData
}

var file_purekitV3_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_purekitV3_grant_proto_goTypes = []interface{}{
	(*EncryptedGrantHeader)(nil), // 0: protos.EncryptedGrantHeader
	(*EncryptedGrant)(nil),       // 1: protos.EncryptedGrant
}
var file_purekitV3_grant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purekitV3_grant_proto_init() }
func file_purekitV3_grant_proto_init() {
	if File_purekitV3_grant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_purekitV3_grant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedGrantHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_purekitV3_grant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedGrant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purekitV3_grant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purekitV3_grant_proto_goTypes,
		DependencyIndexes: file_purekitV3_grant_proto_depIdxs,
		MessageInfos:      file_purekitV3_grant_proto_msgTypes,
	}.Build()
	File_purekitV3_grant_proto = out.File
	file_purekitV3_grant_proto_rawDesc = nil
	file_purekitV3_grant_proto_goTypes = nil
	file_purekitV3_grant_proto_depIdxs = nil
}
